# Generated by Django 4.0.4 on 2023-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti')], default='Khalti', max_length=255),
        ),
    ]
