# Generated by Django 4.2.7 on 2023-11-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetOwner',
        ),
    ]
